# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "first-app"
client_id = "4f36507f4df2e5c4d360773ec9cf4c2c"
application_url = "https://decent-win-reference-devon.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://decent-win-reference-devon.trycloudflare.com/auth/callback",
  "https://decent-win-reference-devon.trycloudflare.com/auth/shopify/callback",
  "https://decent-win-reference-devon.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "elena-weekly-how.myshopify.com"
